#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Object-Lexical
version:      0.02
version_from: Lexical.pm
installdirs:  site
requires:
    PadWalker:                     0.08

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
